{
    "bug_id": 29,
    "bug_type": "SL SH SF",
    "buggy_lines": "        description.appendText(wanted.toString());",
    "code": "    public void describeTo(Description description) {\n        description.appendText(\"same(\");\n        appendQuoting(description);\n        description.appendText(wanted.toString());\n        appendQuoting(description);\n        description.appendText(\")\");\n    }",
    "fixed_code": "    public void describeTo(Description description) {\n        description.appendText(\"same(\");\n        appendQuoting(description);\n        description.appendText(wanted == null ? \"null\" : wanted.toString());\n        appendQuoting(description);\n        description.appendText(\")\");\n    }",
    "fixed_lines": "        description.appendText(wanted == null ? \"null\" : wanted.toString());",
    "masked_code": "    public void describeTo(Description description) {\n        description.appendText(\"same(\");\n        appendQuoting(description);\n>>> [ INFILL ] <<<\n        appendQuoting(description);\n        description.appendText(\")\");\n    }",
    "project": "Mockito",
    "test_error_message": "java.lang.Exception: Unexpected exception, expected<java.lang.AssertionError> but was<java.lang.NullPointerException>",
    "test_framework": "defects4j",
    "test_line": "        verify(mock).objectArgMethod(same(null));",
    "test_name": "shouldNotThrowNPEWhenNullPassedToSame",
    "test_suite": "org.mockitousage.bugs.NPEWithCertainMatchersTest",
    "time_buggy": "2010-11-18 15:53:29 +0100",
    "time_fixed": "2010-11-18 17:54:14 +0100"
}